"""agregar_tablas_equipos_tickets_comentarios

Revision ID: 0a24d5dcc41b
Revises: b217285236f5
Create Date: 2026-02-13 15:51:47.887554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a24d5dcc41b'
down_revision: Union[str, Sequence[str], None] = 'b217285236f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
