"""Agregar notificaciones y tablas de manuales

Revision ID: 135cfa074b99
Revises: 0a24d5dcc41b
Create Date: 2026-02-19 12:36:22.603496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '135cfa074b99'
down_revision: Union[str, Sequence[str], None] = '0a24d5dcc41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nombre'), 'users', ['nombre'], unique=False)
    op.drop_index(op.f('ix_reportes_anomalias_id'), table_name='reportes_anomalias')
    op.drop_table('reportes_anomalias')
    op.drop_index(op.f('ix_logs_eventos_id'), table_name='logs_eventos')
    op.drop_table('logs_eventos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    #op.drop_constraint('equipos_cliente_id_fkey', 'equipos', type_='foreignkey')
    #op.drop_table('usuarios')
    op.execute("DROP TABLE IF EXISTS usuarios CASCADE")
    # op.drop_constraint(op.f('equipos_cliente_id_fkey'), 'equipos', type_='foreignkey')
    op.create_foreign_key(None, 'equipos', 'users', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.create_foreign_key(op.f('equipos_cliente_id_fkey'), 'equipos', 'usuarios', ['cliente_id'], ['id'])
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('usuarios_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('logs_eventos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('equipo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], name=op.f('logs_eventos_equipo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_eventos_pkey'))
    )
    op.create_index(op.f('ix_logs_eventos_id'), 'logs_eventos', ['id'], unique=False)
    op.create_table('reportes_anomalias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('equipo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion_cliente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoria_ia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prioridad_ia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_reporte', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], name=op.f('reportes_anomalias_cliente_id_fkey')),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], name=op.f('reportes_anomalias_equipo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reportes_anomalias_pkey'))
    )
    op.create_index(op.f('ix_reportes_anomalias_id'), 'reportes_anomalias', ['id'], unique=False)
    op.drop_index(op.f('ix_users_nombre'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
