"""crear tabla de tickets

Revision ID: 18ab49c71c09
Revises: 610f06a5f24f
Create Date: 2026-02-05 12:29:08.001480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ab49c71c09'
down_revision: Union[str, Sequence[str], None] = '610f06a5f24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_cliente', sa.Text(), nullable=False),
    sa.Column('status_reporte', sa.String(), nullable=True),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('categoria_ia', sa.String(), nullable=True),
    sa.Column('prioridad_ia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
