"""crear tabla de logs_eventos

Revision ID: 216749b9b07d
Revises: e990584d514f
Create Date: 2026-02-05 13:35:09.743192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '216749b9b07d'
down_revision: Union[str, Sequence[str], None] = 'e990584d514f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs_eventos', 'equipo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logs_eventos', 'evento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs_eventos', 'detalles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs_eventos', 'detalles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('logs_eventos', 'evento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logs_eventos', 'equipo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
