"""Agregar tabla ticket_attachments

Revision ID: 25616917603f
Revises: 279286dd94b2
Create Date: 2026-03-04 16:26:38.778683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25616917603f'
down_revision: Union[str, Sequence[str], None] = '279286dd94b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_eventos_id'), 'log_eventos', ['id'], unique=False)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.drop_index(op.f('ix_base_conocimiento_ia_id'), table_name='base_conocimiento_ia')
    op.drop_index(op.f('ix_base_conocimiento_ia_titulo'), table_name='base_conocimiento_ia')
    op.drop_table('base_conocimiento_ia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_conocimiento_ia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contenido_texto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector_embedding', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('ultima_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('base_conocimiento_ia_pkey'))
    )
    op.create_index(op.f('ix_base_conocimiento_ia_titulo'), 'base_conocimiento_ia', ['titulo'], unique=False)
    op.create_index(op.f('ix_base_conocimiento_ia_id'), 'base_conocimiento_ia', ['id'], unique=False)
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_ticket_attachments_id'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index(op.f('ix_log_eventos_id'), table_name='log_eventos')
    op.drop_table('log_eventos')
    # ### end Alembic commands ###
