"""Agregar columna descripcion a roles

Revision ID: 279286dd94b2
Revises: 7276466bce74
Create Date: 2026-03-01 13:52:09.849511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279286dd94b2'
down_revision: Union[str, Sequence[str], None] = '7276466bce74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte_anomalias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_anomalias_id'), 'reporte_anomalias', ['id'], unique=False)
    op.add_column('roles', sa.Column('descripcion', sa.String(), nullable=True))
    op.alter_column('roles', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('roles', 'descripcion')
    op.drop_index(op.f('ix_reporte_anomalias_id'), table_name='reporte_anomalias')
    op.drop_table('reporte_anomalias')
    # ### end Alembic commands ###
