"""Initial migration

Revision ID: 610f06a5f24f
Revises: 
Create Date: 2026-02-02 23:48:49.857341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610f06a5f24f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_conocimiento_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('contenido_texto', sa.Text(), nullable=True),
    sa.Column('vector_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_conocimiento_ia_id'), 'base_conocimiento_ia', ['id'], unique=False)
    op.create_index(op.f('ix_base_conocimiento_ia_titulo'), 'base_conocimiento_ia', ['titulo'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EN_TRANSITO', 'RECIBIDO', 'INSTALADO', name='statusequipo'), nullable=True),
    sa.Column('fecha_salida_sucursal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_index(op.f('ix_equipos_modelo'), 'equipos', ['modelo'], unique=False)
    op.create_index(op.f('ix_equipos_numero_serie'), 'equipos', ['numero_serie'], unique=True)
    op.create_table('garantias_licencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('HARDWARE', 'SOFTWARE', name='tipogarantia'), nullable=True),
    sa.Column('nombre_software', sa.String(), nullable=True),
    sa.Column('licencia_key', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garantias_licencias_id'), 'garantias_licencias', ['id'], unique=False)
    op.create_table('logs_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('evento', sa.String(), nullable=True),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_eventos_id'), 'logs_eventos', ['id'], unique=False)
    op.create_table('reportes_anomalias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_cliente', sa.Text(), nullable=True),
    sa.Column('categoria_ia', sa.String(), nullable=True),
    sa.Column('prioridad_ia', sa.String(), nullable=True),
    sa.Column('status_reporte', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_anomalias_id'), 'reportes_anomalias', ['id'], unique=False)
    op.create_table('seguimiento_instalacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('estado_empaque', sa.String(), nullable=True),
    sa.Column('confirmacion_encendido', sa.Boolean(), nullable=True),
    sa.Column('evidencia_url', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id')
    )
    op.create_index(op.f('ix_seguimiento_instalacion_id'), 'seguimiento_instalacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguimiento_instalacion_id'), table_name='seguimiento_instalacion')
    op.drop_table('seguimiento_instalacion')
    op.drop_index(op.f('ix_reportes_anomalias_id'), table_name='reportes_anomalias')
    op.drop_table('reportes_anomalias')
    op.drop_index(op.f('ix_logs_eventos_id'), table_name='logs_eventos')
    op.drop_table('logs_eventos')
    op.drop_index(op.f('ix_garantias_licencias_id'), table_name='garantias_licencias')
    op.drop_table('garantias_licencias')
    op.drop_index(op.f('ix_equipos_numero_serie'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_modelo'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_base_conocimiento_ia_titulo'), table_name='base_conocimiento_ia')
    op.drop_index(op.f('ix_base_conocimiento_ia_id'), table_name='base_conocimiento_ia')
    op.drop_table('base_conocimiento_ia')
    # ### end Alembic commands ###
