"""Agregar modelo EquipmentLog

Revision ID: 7276466bce74
Revises: 6a7b8c9d0e1f
Create Date: 2026-03-01 12:13:46.374131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7276466bce74'
down_revision: Union[str, Sequence[str], None] = '6a7b8c9d0e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_logs_id'), 'equipment_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_constraint(op.f('comments_ticket_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tickets', ['ticket_id'], ['id'])
    op.drop_index(op.f('ix_ticket_logs_ticket_id'), table_name='ticket_logs')
    op.drop_constraint(op.f('ticket_logs_ticket_id_fkey'), 'ticket_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_logs', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('tickets', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)

    # --- CORRECCIÓN MANUAL PARA ENUMS EN POSTGRESQL ---
    # 1. Creamos los tipos Enum explícitamente en la base de datos
    ticketstatus_enum = postgresql.ENUM('ABIERTO', 'EN_PROGRESO', 'CERRADO', name='ticketstatus')
    ticketstatus_enum.create(op.get_bind())
    
    ticketpriority_enum = postgresql.ENUM('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='ticketpriority')
    ticketpriority_enum.create(op.get_bind())

    # 2. Alteramos las columnas convirtiendo los datos de texto existentes al nuevo tipo (casting)
    op.execute("ALTER TABLE tickets ALTER COLUMN estado TYPE ticketstatus USING estado::ticketstatus")
    op.execute("ALTER TABLE tickets ALTER COLUMN prioridad TYPE ticketpriority USING prioridad::ticketpriority")

    # Comentamos las operaciones originales de Alembic que causaban el error
    # op.alter_column('tickets', 'estado',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('ABIERTO', 'EN_PROGRESO', 'CERRADO', name='ticketstatus'),
    #            existing_nullable=True)
    # op.alter_column('tickets', 'prioridad',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='ticketpriority'),
    #            existing_nullable=True)
    # --------------------------------------------------
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- CORRECCIÓN MANUAL PARA REVERTIR ENUMS EN POSTGRESQL ---
    # 1. Regresamos las columnas a su tipo original de texto
    op.execute("ALTER TABLE tickets ALTER COLUMN prioridad TYPE VARCHAR(50) USING prioridad::VARCHAR")
    op.execute("ALTER TABLE tickets ALTER COLUMN estado TYPE VARCHAR(50) USING estado::VARCHAR")

    # 2. Eliminamos los tipos Enum de PostgreSQL
    ticketstatus_enum = postgresql.ENUM('ABIERTO', 'EN_PROGRESO', 'CERRADO', name='ticketstatus')
    ticketstatus_enum.drop(op.get_bind())
    
    ticketpriority_enum = postgresql.ENUM('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='ticketpriority')
    ticketpriority_enum.drop(op.get_bind())

    # Comentamos las operaciones de rollback defectuosas
    # op.alter_column('tickets', 'prioridad',
    #            existing_type=sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='ticketpriority'),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    # op.alter_column('tickets', 'estado',
    #            existing_type=sa.Enum('ABIERTO', 'EN_PROGRESO', 'CERRADO', name='ticketstatus'),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    # -----------------------------------------------------------

    op.alter_column('tickets', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'ticket_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_logs_ticket_id_fkey'), 'ticket_logs', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_ticket_logs_ticket_id'), 'ticket_logs', ['ticket_id'], unique=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_ticket_id_fkey'), 'comments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mensaje', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('leida', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('notifications_ticket_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_index(op.f('ix_equipment_logs_id'), table_name='equipment_logs')
    op.drop_table('equipment_logs')
    # ### end Alembic commands ###
