"""agrega_campos_vencimiento_licencias

Revision ID: 7ae8c9d4d923
Revises: 25616917603f
Create Date: 2026-03-05 11:33:13.488634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ae8c9d4d923'
down_revision: Union[str, Sequence[str], None] = '25616917603f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Crear el tipo Enum en PostgreSQL ANTES de agregar la columna
    licensetype = postgresql.ENUM('Suscripcion', 'Perpetua', name='licensetype')
    licensetype.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.add_column('licenses', sa.Column('equipment_id', sa.Integer(), nullable=False))
    op.add_column('licenses', sa.Column('nombre_software', sa.String(length=255), nullable=False))
    op.add_column('licenses', sa.Column('tipo_licencia', sa.Enum('Suscripcion', 'Perpetua', name='licensetype'), nullable=False))
    op.add_column('licenses', sa.Column('fecha_inicio', sa.Date(), nullable=False))
    op.add_column('licenses', sa.Column('fecha_vencimiento', sa.Date(), nullable=True))
    op.add_column('licenses', sa.Column('clave_producto', sa.String(length=255), nullable=True))
    op.add_column('licenses', sa.Column('archivo_url', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_licenses_equipment_id'), 'licenses', ['equipment_id'], unique=False)
    op.drop_constraint(op.f('licenses_equipo_id_fkey'), 'licenses', type_='foreignkey')
    op.create_foreign_key(None, 'licenses', 'equipos', ['equipment_id'], ['id'])
    op.drop_column('licenses', 'file_path')
    op.drop_column('licenses', 'product_key')
    op.drop_column('licenses', 'equipo_id')
    op.drop_column('licenses', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('equipo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('licenses', sa.Column('product_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.create_foreign_key(op.f('licenses_equipo_id_fkey'), 'licenses', 'equipos', ['equipo_id'], ['id'])
    op.drop_index(op.f('ix_licenses_equipment_id'), table_name='licenses')
    op.drop_column('licenses', 'archivo_url')
    op.drop_column('licenses', 'clave_producto')
    op.drop_column('licenses', 'fecha_vencimiento')
    op.drop_column('licenses', 'fecha_inicio')
    op.drop_column('licenses', 'tipo_licencia')
    op.drop_column('licenses', 'nombre_software')
    op.drop_column('licenses', 'equipment_id')
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('comments_ticket_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('comments_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    # ### end Alembic commands ###

    # 2. Eliminar el tipo Enum en PostgreSQL DESPUÉS de quitar la columna
    licensetype = postgresql.ENUM('Suscripcion', 'Perpetua', name='licensetype')
    licensetype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
