"""Agregar campos de recepcion a equipos

Revision ID: 7b5c86f8be3e
Revises: c241cd35eaa3
Create Date: 2026-03-05 07:57:34.200622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5c86f8be3e'
down_revision: Union[str, Sequence[str], None] = 'c241cd35eaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipos', sa.Column('estado_empaque', sa.String(), nullable=True))
    op.add_column('equipos', sa.Column('confirmacion_encendido', sa.Boolean(), nullable=True))
    op.add_column('equipos', sa.Column('fecha_recepcion', sa.DateTime(), nullable=True))
    op.add_column('equipos', sa.Column('fecha_vencimiento_garantia', sa.DateTime(), nullable=True))
    op.add_column('equipos', sa.Column('ruta_evidencia', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipos', 'ruta_evidencia')
    op.drop_column('equipos', 'fecha_vencimiento_garantia')
    op.drop_column('equipos', 'fecha_recepcion')
    op.drop_column('equipos', 'confirmacion_encendido')
    op.drop_column('equipos', 'estado_empaque')
    # ### end Alembic commands ###
