"""nuevos_campos_garantias

Revision ID: 801c086b3af8
Revises: 90139a3fccb6
Create Date: 2026-04-09 05:02:09.330026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801c086b3af8'
down_revision: Union[str, Sequence[str], None] = '90139a3fccb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garantias_licencias', sa.Column('folio', sa.String(), nullable=True))
    op.add_column('garantias_licencias', sa.Column('fecha_reporte', sa.Date(), nullable=True))
    op.add_column('garantias_licencias', sa.Column('ejecutivo_cargo', sa.String(), nullable=True))
    op.add_column('garantias_licencias', sa.Column('marca', sa.String(), nullable=True))
    op.add_column('garantias_licencias', sa.Column('proveedor', sa.String(), nullable=True))
    op.create_index(op.f('ix_garantias_licencias_folio'), 'garantias_licencias', ['folio'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garantias_licencias_folio'), table_name='garantias_licencias')
    op.drop_column('garantias_licencias', 'proveedor')
    op.drop_column('garantias_licencias', 'marca')
    op.drop_column('garantias_licencias', 'ejecutivo_cargo')
    op.drop_column('garantias_licencias', 'fecha_reporte')
    op.drop_column('garantias_licencias', 'folio')
    # ### end Alembic commands ###
