"""agrega_apellidos_y_datos_user

Revision ID: 90139a3fccb6
Revises: dd5898583ebc
Create Date: 2026-04-06 08:28:08.343092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90139a3fccb6'
down_revision: Union[str, Sequence[str], None] = 'dd5898583ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo agregamos las columnas nuevas a la tabla 'users'
    op.add_column('users', sa.Column('apellidos', sa.String(), nullable=True))
    op.add_column('users', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telefono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo eliminamos las columnas nuevas de la tabla 'users' en caso de revertir
    op.drop_column('users', 'telefono')
    op.drop_column('users', 'direccion')
    op.drop_column('users', 'apellidos')
    # ### end Alembic commands ###