"""agrega_apellidos_y_datos_user

Revision ID: 90139a3fccb6
Revises: dd5898583ebc
Create Date: 2026-04-06 08:28:08.343092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90139a3fccb6'
down_revision: Union[str, Sequence[str], None] = 'dd5898583ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_ticket_id'), 'comentarios_ticket', ['id'], unique=False)
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.add_column('ticket_attachments', sa.Column('uploaded_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ticket_attachments', 'users', ['uploaded_by_id'], ['id'])
    op.add_column('tickets', sa.Column('status', sa.Enum('ABIERTO', 'EN_PROGRESO', 'RESUELTO', 'CERRADO', name='ticketstatus'), nullable=True))
    op.add_column('tickets', sa.Column('categoria', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('fecha_agendada', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tickets', 'estado')
    op.drop_column('tickets', 'fecha_creacion')
    op.add_column('users', sa.Column('apellidos', sa.String(), nullable=True))
    op.add_column('users', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telefono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telefono')
    op.drop_column('users', 'direccion')
    op.drop_column('users', 'apellidos')
    op.add_column('tickets', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('estado', postgresql.ENUM('ABIERTO', 'EN_PROGRESO', 'CERRADO', name='ticketstatus'), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'created_at')
    op.drop_column('tickets', 'fecha_agendada')
    op.drop_column('tickets', 'categoria')
    op.drop_column('tickets', 'status')
    op.drop_constraint(None, 'ticket_attachments', type_='foreignkey')
    op.drop_column('ticket_attachments', 'uploaded_by_id')
    op.create_table('ticket_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_comments_ticket_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('ticket_comments_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_comments_pkey'))
    )
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.drop_index(op.f('ix_comentarios_ticket_id'), table_name='comentarios_ticket')
    op.drop_table('comentarios_ticket')
    # ### end Alembic commands ###
