"""agregar_campos_perfil_usuario

Revision ID: a1392c5d5c59
Revises: 0a24d5dcc41b
Create Date: 2026-03-03 01:26:17.421468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1392c5d5c59'
down_revision: Union[str, Sequence[str], None] = '0a24d5dcc41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_eventos_id'), table_name='logs_eventos')
    op.drop_table('logs_eventos')
    op.add_column('usuarios', sa.Column('apellidos', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('telefono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'telefono')
    op.drop_column('usuarios', 'direccion')
    op.drop_column('usuarios', 'apellidos')
    op.create_table('logs_eventos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('equipo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], name=op.f('logs_eventos_equipo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_eventos_pkey'))
    )
    op.create_index(op.f('ix_logs_eventos_id'), 'logs_eventos', ['id'], unique=False)
    # ### end Alembic commands ###
