"""Agrega tabla para chat de garantias

Revision ID: a2b76f6d309a
Revises: 801c086b3af8
Create Date: 2026-04-16 06:44:30.869392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b76f6d309a'
down_revision: Union[str, Sequence[str], None] = '801c086b3af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencia_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licencia_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=1000), nullable=False),
    sa.Column('archivo_url', sa.String(length=512), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['licencia_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licencia_comments_id'), 'licencia_comments', ['id'], unique=False)
    op.create_index(op.f('ix_licencia_comments_licencia_id'), 'licencia_comments', ['licencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licencia_comments_licencia_id'), table_name='licencia_comments')
    op.drop_index(op.f('ix_licencia_comments_id'), table_name='licencia_comments')
    op.drop_table('licencia_comments')
    # ### end Alembic commands ###
