"""Agregar categoria IA a tickets

Revision ID: c00b3fb2aafc
Revises: 7b5c86f8be3e
Create Date: 2026-03-05 08:46:40.308943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00b3fb2aafc'
down_revision: Union[str, Sequence[str], None] = '7b5c86f8be3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('categoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'categoria')
    # ### end Alembic commands ###
