"""agregar_campos_perfil_usuario

Revision ID: c241cd35eaa3
Revises: a1392c5d5c59
Create Date: 2026-03-03 01:28:51.545889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c241cd35eaa3'
down_revision: Union[str, Sequence[str], None] = 'a1392c5d5c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
