"""add filename to license

Revision ID: dd5898583ebc
Revises: f7dcef2173df
Create Date: 2026-03-17 13:28:58.518450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5898583ebc'
down_revision: Union[str, Sequence[str], None] = 'f7dcef2173df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_equipos_numero_serie'), 'equipos', type_='unique')
    op.add_column('licenses', sa.Column('filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'filename')
    op.create_unique_constraint(op.f('uq_equipos_numero_serie'), 'equipos', ['numero_serie'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
