"""agregar tabla log_eventos y campos de recepcion en equipos

Revision ID: ffa414015326
Revises: 922c0c54e130
Create Date: 2026-02-13 13:48:40.291635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffa414015326'
down_revision: Union[str, Sequence[str], None] = '922c0c54e130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs_eventos', 'equipo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('logs_eventos', 'evento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logs_eventos', 'detalles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs_eventos', 'detalles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('logs_eventos', 'evento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs_eventos', 'equipo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
